---
- hosts: all
  become: yes
  tasks:
    - name: Instalar dependências
      apt:
        pkg:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present

    - name: Adicionar chave GPG do repositório Zabbix
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Adicionar repositório Zabbix
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu $(lsb_release -cs) main"
        state: present

    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Instalar Zabbix Agent2
      apt:
        pkg: zabbix-agent2
        state: present

    - name: Iniciar e habilitar Zabbix Agent2
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: started
